# Generated by Django 4.2.7 on 2024-02-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_studentreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentreview',
            new_name='review',
        ),
    ]
